feat: updating and compatibility
hydra-genetics/parabricks pull request #18
Opened 2022-05-09 09:33 UTC by marrip

2022-05-09 09:41 UTC, jonca79 approved these changes

2022-05-09 10:37 UTC, Smeds requested changes

2022-05-09 10:37 UTC, Smeds commented on .github/workflows/compatibility.yaml
> +          echo $CONDA/bin >> $GITHUB_PATH
could we remove conda settings? It's not used.

2022-05-09 10:37 UTC, Smeds commented on .github/workflows/compatibility.yaml
> +          snakemake -n -s Snakefile -c
Is "-c" needed?

2022-05-09 10:37 UTC, Smeds commented on .github/workflows/compatibility.yaml
> +          snakemake -n -s Snakefile
should be removed?

2022-05-16 09:14 UTC, Smeds approved these changes

2022-05-16 09:14 UTC, merged